In [32]:
import pandas
import time
import torch
import math
from graph2graphcnn import UniformGraph2GraphCNN
from graph2graphcnn import GraphMSELoss

In [2]:
losses_df = pandas.DataFrame({'coordtype':pandas.Series(dtype='str'), 'batchsize':pandas.Series(dtype='int'), 'graphconvolutions':pandas.Series(dtype='int'), 'mlplayers':pandas.Series(dtype='int'), 'repdims':pandas.Series(dtype='int'), 'optimizer':pandas.Series(dtype='str'), 'learningrate':pandas.Series(dtype='float'), 'trainingrmse':pandas.Series(dtype='float'), 'validationrmse':pandas.Series(dtype='float'), 'time':pandas.Series(dtype='float')})
print(losses_df)

Empty DataFrame
Columns: [coordtype, batchsize, graphconvolutions, mlplayers, repdims, optimizer, learningrate, trainingrmse, validationrmse, time]
Index: []


In [3]:
coordinate_type_name = 'rectangular'
batch_size = 0
graph_convolution_layers = 0
mlp_hidden_layers = 0
rep_dims = 0
optimizer_name = 'Adam'
learning_rate = 0.001
for i in range(10):
    dfrow = pandas.DataFrame({'coordtype':coordinate_type_name, 'batchsize':batch_size, 'graphconvolutions':graph_convolution_layers, 'mlplayers':mlp_hidden_layers, 'repdims':rep_dims, 'optimizer':optimizer_name, 'learningrate':learning_rate, 'trainingrmse':0.0, 'validationrmse':0.0, 'time':-1.0},index=[i])
    losses_df = pandas.concat([losses_df, dfrow], ignore_index=True)
print(losses_df)

     coordtype  batchsize  graphconvolutions  mlplayers  repdims optimizer  \
0  rectangular          0                  0          0        0      Adam   
1  rectangular          0                  0          0        0      Adam   
2  rectangular          0                  0          0        0      Adam   
3  rectangular          0                  0          0        0      Adam   
4  rectangular          0                  0          0        0      Adam   
5  rectangular          0                  0          0        0      Adam   
6  rectangular          0                  0          0        0      Adam   
7  rectangular          0                  0          0        0      Adam   
8  rectangular          0                  0          0        0      Adam   
9  rectangular          0                  0          0        0      Adam   

   learningrate  trainingrmse  validationrmse  time  
0         0.001           0.0             0.0  -1.0  
1         0.001           0.0    

In [5]:
for i in range(5):
    losses_df.at[i,'time']= time.time()
print(losses_df)

     coordtype  batchsize  graphconvolutions  mlplayers  repdims optimizer  \
0  rectangular          0                  0          0        0      Adam   
1  rectangular          0                  0          0        0      Adam   
2  rectangular          0                  0          0        0      Adam   
3  rectangular          0                  0          0        0      Adam   
4  rectangular          0                  0          0        0      Adam   
5  rectangular          0                  0          0        0      Adam   
6  rectangular          0                  0          0        0      Adam   
7  rectangular          0                  0          0        0      Adam   
8  rectangular          0                  0          0        0      Adam   
9  rectangular          0                  0          0        0      Adam   

   learningrate  trainingrmse  validationrmse          time  
0         0.001           0.0             0.0  1.718791e+09  
1         0.001  

In [13]:
print( losses_df.loc[losses_df['time'] != -1.0] )

     coordtype  batchsize  graphconvolutions  mlplayers  repdims optimizer  \
0  rectangular          0                  0          0        0      Adam   
1  rectangular          0                  0          0        0      Adam   
2  rectangular          0                  0          0        0      Adam   
3  rectangular          0                  0          0        0      Adam   
4  rectangular          0                  0          0        0      Adam   

   learningrate  trainingrmse  validationrmse          time  
0         0.001           0.0             0.0  1.718791e+09  
1         0.001           0.0             0.0  1.718791e+09  
2         0.001           0.0             0.0  1.718791e+09  
3         0.001           0.0             0.0  1.718791e+09  
4         0.001           0.0             0.0  1.718791e+09  


In [15]:
first_unfilled = losses_df.loc[losses_df['time'] == -1.0].iloc[0]
print(first_unfilled)

coordtype            rectangular
batchsize                      0
graphconvolutions              0
mlplayers                      0
repdims                        0
optimizer                   Adam
learningrate               0.001
trainingrmse                 0.0
validationrmse               0.0
time                        -1.0
Name: 5, dtype: object


In [16]:
num_filled = len(losses_df.loc[losses_df['time'] != -1.0].index)
print(num_filled)

5


In [22]:
min_batch_size = 10
max_batch_size = 100
num_batch_sizes = 3
device = torch.device('cuda')
batch_sizes = torch.exp( torch.linspace( start=math.log(min_batch_size), end=math.log(max_batch_size), steps=num_batch_sizes, dtype=torch.float, device=device ) ).int()
print(batch_sizes)

tensor([ 10,  31, 100], device='cuda:0', dtype=torch.int32)


In [37]:
g2gcnn = UniformGraph2GraphCNN(num_node_in_features=7, num_edge_in_features=1, num_node_out_features=1, num_edge_out_features=1, mlp_hidden_width=2, num_node_mlp_hidden_layers=1, num_edge_mlp_hidden_layers=1, num_graph_message_passes=1, dtype=torch.float, device=device)
print( g2gcnn.parameters() )

making Graph2GraphCNN with layer widths
[([7, 2], [1, 2]), ([4, 1], [6, 1])]
<generator object Module.parameters at 0x0000022A3DFA7DF0>


In [38]:
for parameter in g2gcnn.parameters():
    print(parameter)

Parameter containing:
tensor([[-0.1939, -0.3765,  0.1866,  0.0676,  0.3715, -0.0574, -0.0509],
        [ 0.0451,  0.0827, -0.1825, -0.0102, -0.0823, -0.0942,  0.3748]],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.2988, -0.3493], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([[-0.4958],
        [-0.0946]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.1067, -0.8184], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([[-0.3133,  0.4732, -0.4972, -0.1466]], device='cuda:0',
       requires_grad=True)
Parameter containing:
tensor([-0.4985], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([[-0.2866,  0.1512,  0.2921, -0.2444, -0.0808,  0.0135]],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.2949], device='cuda:0', requires_grad=True)


In [39]:
optimizer = torch.optim.Adam( params=g2gcnn.parameters(), lr=learning_rate )
print(optimizer)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)


In [40]:
optimizer.zero_grad()

In [41]:
h_pred, J_pred = g2gcnn(node_in_features=torch.rand( (3,360,7), dtype=torch.float, device=device ), edge_in_features=torch.rand( (3,360,360,1), dtype=torch.float, device=device ))
print(h_pred.size(), J_pred.size())

torch.Size([3, 360, 1]) torch.Size([3, 360, 360, 1])


In [42]:
loss_fn = GraphMSELoss(num_nodes=360, dtype=torch.float, device=device)
print(loss_fn)

GraphMSELoss(
  (simple_mse_loss): MSELoss()
)


In [43]:
loss = loss_fn(node_features_pred=h_pred, edge_features_pred=J_pred, node_features_target=torch.rand( (3,360,1), dtype=torch.float, device=device ), edge_features_target=torch.rand( (3,360,360,1), dtype=torch.float, device=device ))
print(loss)

tensor(0.3344, device='cuda:0', grad_fn=<DivBackward0>)


In [44]:
loss.backward()

In [45]:
optimizer.step()